export const LangStrings = {
  en: {
    welcome: "Welcome",
    newtaskbuttonlabel: "New Task",
    newtask: "New task",
    settings: "Settings",
    urlplaceholder: "Database URL, leave empty to connect to the default local database",
    usernameplaceholder: "Username, leave empy to keep yourself anonymous",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    title: "Title",
    description: "Description",
    add: "Add",
    cancel: "Cancel",
  },
  it: {
    welcome: "Benvenuto",
    newtaskbuttonlabel: "Nuovo Compito",
    newtask: "Nuovo compito",
    settings: "Impostazioni",
    urlplaceholder: "URL del database, lascia vuoto per connetterti al database locale",
    usernameplaceholder: "Nome utente, lascia vuoto per rimanere anonimo",
    january: "Gennaio",
    february: "Febbraio",
    march: "Marzo",
    april: "Aprile",
    may: "Maggio",
    june: "Giugno",
    july: "Luglio",
    august: "Agosto",
    september: "Settembre",
    october: "Ottobre",
    november: "Novembre",
    december: "Dicembre",
    title: "Titolo",
    description: "Descrizione",
    add: "Aggiungi",
    cancel: "Annulla",
  },
}