export const LangStrings = {
  en: {
    welcome: "Welcome",
    newtaskbuttonlabel: "New Task",
    newtask: "New task",
    settings: "Settings",
    urlplaceholder: "Database URL, leave empty to connect to the default local database",
    usernameplaceholder: "Username, leave empy to keep yourself anonymous",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    title: "Title",
    description: "Description",
    add: "Add",
    cancel: "Cancel",
    username: "Username",
    databaseURL: "Database URL",
    save: "Save",
    english: "English",
    italian: "Italian",
    language: "Language",
    nothingtoseehere: "Nothing to see here.",
    edittitle: "Edit",
    pressCTRL: "Long-press CTRL to go back",
    beforestarting: "Before you start...",
    stilltesting: "This app is still in its test phase",
    expectbugs: "Expect bugs, errors and also unexpected crashes",
    editmode: "Edit mode",
    editmodedesc: "Long-press CTRL to activate it, from here you can edit and delete tasks",
    close: "Close",
  },
  it: {
    welcome: "Benvenuto",
    newtaskbuttonlabel: "Nuovo Compito",
    newtask: "Nuovo compito",
    settings: "Impostazioni",
    urlplaceholder: "URL del database, lascia vuoto per connetterti al database locale",
    usernameplaceholder: "Nome utente, lascia vuoto per rimanere anonimo",
    january: "Gennaio",
    february: "Febbraio",
    march: "Marzo",
    april: "Aprile",
    may: "Maggio",
    june: "Giugno",
    july: "Luglio",
    august: "Agosto",
    september: "Settembre",
    october: "Ottobre",
    november: "Novembre",
    december: "Dicembre",
    title: "Titolo",
    description: "Descrizione",
    add: "Aggiungi",
    cancel: "Annulla",
    username: "Nome utente",
    databaseURL: "URL Database",
    save: "Salva",
    english: "Inglese",
    italian: "Italiano",
    language: "Lingua",
    nothingtoseehere: "Niente da vedere qui.",
    edittitle: "Modifica",
    pressCTRL: "Tieni premuto CTRL per tornare indietro",
    beforestarting: "Prima di iniziare...",
    stilltesting: "Il programma è ancora in fase di test",
    expectbugs: "Aspettati bug, errori e anche crash improvvisi",
    editmode: "Modalità modifica",
    editmodedesc: "Tieni premuto CTRL per attivarla, da qui potrai modificare o eliminare i compiti assegnati",
    close: "Chiudi",
  },
}